server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Habilita react-router para funcionar correctamente al recargar páginas
        try_files $uri $uri/ /index.html;
    }
}
